server:
  port: ${port:8501}

eureka:
  instance:
    hostname: ${hostname:eureka}
  client:
    register-with-eureka: false
    serviceUrl:
          defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}
    fetch-registry: false