spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xianguangHu/store
          username: 15789762@qq.com
          password: hxg125678
          search-paths: /*

server:
  port: 8502
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8501/eureka/

