spring:
  application:
    admin: cloud-config
  cloud:
    config:
      server:
      label: master
        git:
          url: https://gitee.com/Xg_Hu/xbin-store-cloud.git
          username: Xg_Hu
          password: hxg125678
          search-paths: /config/*


server:
  port: 8502
